default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("LOCAL_DB_HOST") { ENV.fetch("DB_HOST", "localhost") } %>
  port: <%= ENV.fetch("LOCAL_DB_PORT") { ENV.fetch("DB_PORT", 5432) } %>
  username: <%= ENV.fetch("LOCAL_DB_USERNAME") { ENV.fetch("DB_USERNAME", "postgres") } %>
  password: <%= ENV.fetch("LOCAL_DB_PASSWORD") { ENV.fetch("DB_PASSWORD", "") } %>

production:
  <<: *default
  database: tempra_production
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: tempra_development

test:
  <<: *default
  database: tempra_test
